Refact/#42 User Domain
VoicePocket/VoicePocket-Backend-new pull request #43
Opened 2024-03-09 15:07 UTC by tidavid1

## 리펙토링 내역
- `User` Entity 의 일부 Field 가 변경되었습니다.
  - String[] roles -> `UserRole` role
  - `deletedAt` 추가
    - 필드 추가에 따라 `deleteUser` 로직을 변경했습니다.
    - `isEnabled` 로직을 변경했습니다.
    - 유저 조회 쿼리를 수정했습니다.
- User Entity 생성시 검증 로직을 추가했습니다.
- `Email` VO를 추가하여 이메일을 전달 받았을 시 검증할 수 있도록 했습니다.
- SpringBoot Validation 의존을 추가했습니다.
  - `RequestBody`로 전달받는 값들에 대한 검증 로직이 추가되었습니다.

2024-03-14 07:46 UTC, hi-june reviewed
리펙토링 작업하시느라 고생하셨습니다. 👍
몇 가지 궁금한 점들은 아래 리뷰 추가로 남기겠습니다!

2024-03-14 07:50 UTC, hi-june commented on voicepocket/src/main/java/com/vp/voicepocket/domain/user/entity/vo/Email.java
> +}
validation 의존성 추가하신걸 보니 기본적으로 @Email 어노테이션을 통해 컨트롤러단에서 검증을 해주시고 계신 것 같은데, Email VO를 통해 한 번 더 검증을 해주시는 이유가 있을까요~?

2024-03-14 07:58 UTC, hi-june commented on voicepocket/src/main/java/com/vp/voicepocket/domain/user/repository/UserRepository.java
> +    Optional<User> findByEmail(@NonNull String email);
@NonNull과 @NotNull의 차이가 무엇인가요? (궁금증)

2024-03-14 08:00 UTC, hi-june commented on voicepocket/src/main/java/com/vp/voicepocket/domain/user/entity/User.java
> +    private Long id;
엔티티 필드명을 userId에서 id로 바꾸면서, 테이블의 칼럼명도 id로 수정하신 것 같은데, 팔로우 신청 기능에 외래키로 매핑 되는 부분의 칼럼명도 한 번 살펴보셔야될 것 같습니다.

2024-03-14 08:03 UTC, hi-june requested changes
리뷰 완료했습니다!
궁금 부분이 몇 부분 있는데, 답변 주시면 확인해보겠습니당

2024-03-14 08:44 UTC, tidavid1 commented on voicepocket/src/main/java/com/vp/voicepocket/domain/user/entity/vo/Email.java
> +}
`@Email` 어노테이션은 불명확한 형식의 이메일 규격에 대해 Validation이 되지 않는 현상이 존재합니다. [링크](https://see-one.tistory.com/14) 이에 VO를 따로 두어 검증하는 형식으로 코드를 구성했습니다.

2024-03-14 08:48 UTC, tidavid1 commented on voicepocket/src/main/java/com/vp/voicepocket/domain/user/repository/UserRepository.java
> +    Optional<User> findByEmail(@NonNull String email);
`@NotNull` 어노테이션은 하이버네이트에서 제공하는 어노테이션으로 `@Valid`가 존재하지 않으면 동작하지 않습니다. `@NonNull`은 Spring에서 제공하는 자카르타에 포함된 `@Nonnull`을 Wrap한 어노테이션으로 `@Valid` 없이 메서드 값이 null인 경우 NPE를 발생시킵니다.

2024-03-14 08:49 UTC, tidavid1 commented on voicepocket/src/main/java/com/vp/voicepocket/domain/user/repository/UserRepository.java
> +    Optional<User> findByEmail(@NonNull String email);
`@NotNull` 어노테이션은 하이버네이트에서 제공하는 어노테이션으로 `@Valid`가 존재하지 않으면 동작하지 않습니다. `@NonNull`은 Spring에서 제공하는 자카르타에 포함된 `@Nonnull`을 Wrap한 어노테이션으로 `@Valid` 없이 메서드 값이 null인 경우 NPE를 발생시킵니다.

2024-03-15 04:28 UTC, tidavid1 commented on voicepocket/src/main/java/com/vp/voicepocket/domain/user/entity/User.java
> +    private Long id;
[66d9fd9](https://github.com/VoicePocket/VoicePocket-BackendServer/pull/43/commits/66d9fd91137c7edf0c82217e71dd1fed8d2d55c5) 반영완료

2024-03-19 01:13 UTC, hi-june commented on voicepocket/src/main/java/com/vp/voicepocket/domain/user/dto/request/UserSignupRequestDto.java
> +    @javax.validation.constraints.Email
아, 그리고 이 부분 혹시 따로 의도하신건가요?
얘만 어노테이션이 저렇게 되어있어서 질문드립니다!

2024-03-19 01:19 UTC, tidavid1 commented on voicepocket/src/main/java/com/vp/voicepocket/domain/user/dto/request/UserSignupRequestDto.java
> +    @javax.validation.constraints.Email
6번 줄에 `import com.vp.voicepocket.domain.user.entity.vo.Email;`로 Email VO를 갖고와서 어쩔수 없이 어노테이션에서는 직접 갖고오는 방식을 사용했습니다!

2024-03-19 01:29 UTC, hi-june approved these changes

2024-03-19 01:30 UTC, merged